version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.5
      
    steps:
      - checkout
      - run: yarn
      - run: CI=false yarn deploy
      - store_artifacts:
          path: build/mist*.asar
      - store_artifacts:
          path: build/manifest.json

      - run:
          name: "Commiting docs files and publishing module"
          command: |
            if [[ $CIRCLE_BRANCH == 'circleci' ]]; then
              echo "We're on $CIIRCLE_BRANCH branch, deploying..."
              BRANCH=$CIRCLE_BRANCH ./deploy.sh;
            else
              echo "Not on master branch, skipping deployment."
            fi;



