version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.5
      
    steps:
      - checkout
      - run: yarn
      - run: CI=false yarn build:all


      - run:
          name: ""
          command: |
            if [[ $CIRCLE_BRANCH == 'circleci' ]]; then
              echo "We're on $CIIRCLE_BRANCH branch, deploying..."
              BRANCH=$CIRCLE_BRANCH ./deploy.sh;
            else
              echo "Not on master branch, skipping deployment."
            fi;

      - run:
          name: "Copy artifacts"
          command: |
            mkdir -p /tmp/artifacts;
            cp build/manifest.json /tmp/artifacts;
            cp build/metadata.json /tmp/artifacts;

      - store_artifacts:
          path: /tmp/artifacts
